[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
gloo-timers = "0.2"
log = "0.4"
wasm-logger = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["HtmlVideoElement"] }
